### ISSUE TITLE
update all - downloading binaries of the same version

### ISSUE THREAD

**Issue by muralikodali** [DEVLOPRR/bread#3]
using `update --all` downloading all binaries, though there are no new updates for binaries.
above command is also picking wrong version of the binary, i.e arm-64 version (zettlr in my case) instead of linux version.

![screenshot_20220331135028](https://user-images.githubusercontent.com/11482766/161094546-54a99755-d7ed-4ccc-8cc7-c92bfcb1207a.png)

**Comment by pegvin** [comment]
What is the version of bread you are using? (`bread --version`)

**Comment by muralikodali** [comment]
bread version is : `Bread v0.4.4`

**Comment by pegvin** [comment]
This issue was fixed in v0.5.0, but seems like update command is completely broken in v0.5.0 and greater. a patch will be issued soon fixing the issue.
in the mean time i recommend you to watch for new releases, steps are below:

1. Click On Watch button:
![image](https://user-images.githubusercontent.com/75035219/161217103-95e88f63-cadc-41cf-8447-4be1b8b10c27.png)

2. Click On "Custom":
![image](https://user-images.githubusercontent.com/75035219/161217271-cf32d196-2e3e-459d-9cea-370b2f6f61be.png)

And Click on Check the "Releases" Checkbox, and Click Apply.

Now you will be notified for any upcoming releases.

**Comment by pegvin** [comment]
I've Released A Patch Now. [Bread v0.6.2](https://github.com/DEVLOPRR/bread/releases/tag/v0.6.2) is released which fixes bugs

Edit: Bread v0.6.2 Was Removed From Releases As It Was Very Buggy & Unstable

**Comment by muralikodali** [comment]
i have installed v0.6.2. `bread update -all` now also downloading all appimage files.

update also has thrown some errors like `ERROR: appimage_shall_not_be_integrated : Unknown AppImage format: sztheory/exifcleaner`

one positive development is there. instead of downloading zettlr-arm version directly, it now gave option to select the version.

**Comment by DEVLOPRR** [comment]
Try running `bread clean` and then updating it.

**Comment by pegvin** [comment]
Hey There, [Bread v0.7.0](https://github.com/DEVLOPRR/bread/releases/tag/v0.7.0). Which Comes With Alot of Bug Fixes, You Should Try That

**Comment by muralikodali** [comment]
i have downloaded the version 0.7.0. 

working so far so nice. using appimages is now a breeze, as installation got simple just like `sudo pacman -syu'

i would like to suggest two more things for adding more value to the software.

- syncing the appimages using zsync, helps in reducing the download size
- adding gitlab repos also for downloading appimages, enhancing the breadth of appimage availability

as user i have suggested the above things. technically it may be hard to implement.

**Comment by pegvin** [comment]
Lmao, actually I had zsync implemented but I removed it since it made stuff more complicated, but sure I'll implement it again.
And it shouldn't be a pain for gitlab too.
